# Generated by Django 4.1.7 on 2023-04-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('in_stock', models.IntegerField(default=0)),
            ],
        ),
    ]
